### ISSUE TITLE
Sync failure on only one of several devices

### ISSUE THREAD

**Issue by struanb** [iansinnott/prompta#25]
I have several devices syncing, but one of them refuses to sync fully and only has a partial selection of past chats showing the history. I've tried 'Attempt Force DB' and 'Debug Force Sync' and repeatedly but the issue persists.

e.g.
Working device -> Debug Force Sync -> Success ↑ 447,  ↓ 0 (total chats = 11)
Bad device -> Debug Force Sync -> Success ↑ 121,  ↓ 0 (total chats = 4)

I could probably wipe local storage and resync on the bad device (iPhone PWA), but perhaps it would be good to diagnose this issue. Is there anything I can do to help identify the underlying issue?

**Comment by iansinnott** [comment]
Thanks, yeah this sounds like something worth resolving. 

Is it _just_ in the PWA or does regular safari also fail on your phone? could you try?

The thing to do would be to get a debugger session on the offending client. This is pretty straighforward with mobile Safari: Open desktop safari and enable developer mode in settings, then in the top menu bar there should be a "Develop" menu. In there you can open an inspector on your iphone if it's also running.

The app usually logs more information to the console than it displays in the toasts.

**Comment by struanb** [comment]
Bizarrely chat.prompta.dev doesn't even load in my iOS Safari any longer (white screen, progress bar never completes). I'll plug my iPhone into my Mac later to see what's going on.

**Comment by struanb** [comment]
Apologies, you wouldn't believe how hard it is to find a working iPhone charging cable this end, now all my chargers are wireless!

In any case, this issue appears to have been fixed by the recent database migration as all my devices now appear to be in sync, so I will now close this issue.
