### ISSUE TITLE
Angle brackets incorrectly formatted

### ISSUE THREAD

**Issue by struanb** [iansinnott/prompta#27]
Please see the `//` and the `""` shown in this response. I suspected a formatting issue in Prompta and using `await db.execO('select * from message;')` believe I've been able to confirm this.

The actual text to be rendered was:

```
'Apologies for any confusion. "AutofillStates," "ClientSidePhishing," "DesktopSharingHub," and "OnDeviceHeadSuggestModel" are subfolders that generally belong to the Google Chrome browser profile directory.\n\nOn a Mac, you can find these folders within the Chrome profile directory located at:\n\n/Users/<your_username>/Library/Application Support/Google/Chrome/Profile/<profile_number>/\n\nPlease note that "<your_username>" should be replaced with your actual macOS username and "<profile_number>" represents a specific profile number associated with your Chrome user profile.'
```

<img width="942" alt="image" src="https://github.com/iansinnott/prompta/assets/354555/fd85caf3-44e1-4f73-9c8d-804f5265331c">

<img width="1433" alt="image" src="https://github.com/iansinnott/prompta/assets/354555/44a1529f-b54e-4aa5-8009-878e9e96c619">

**Comment by iansinnott** [comment]
To confirm, it's displaying two `//` when there should only be one `/`, right?

**Comment by iansinnott** [comment]
The `<profile>` strings are interesting. Likely something to do with the markdown renderer I'm using

**Comment by iansinnott** [comment]
Note to self: can repro the tag issue in the console with:

```js
insertPendingMessage({content: 'this is "<something>"'})
```

**Comment by struanb** [comment]
That's great, and I think the faulty tag rendering explains all the differences between the example input and output I gave.
