### ISSUE TITLE
Prompta online and on MacOS is not working

### ISSUE THREAD

**Issue by airidasbrikas23** [iansinnott/prompta#54]
After installing on my MacOS, I am malware warning this notification: 
<img width="279" alt="Screenshot 2024-10-31 at 10 52 18" src="https://github.com/user-attachments/assets/5b234aa5-3ac4-4e9d-9576-94d26c0b3bea">

https://chat.prompta.dev/ is also unreachable. I am getting a HTTPS certificate error.

Could some certification have expired or has some malicious code made it into the source?

**Comment by iansinnott** [comment]
Yeah, Apple does that. Apple doesn't want you opening software from someone who doesn't pay Apple for their dev program. 

In the past the way around this was to right click and then click open, but i've heard that is not viable in more recent releases.

The website should be working though. Just checked and it looks fine on my end. It's deployed through Vercel so i don't manage the certificates. Try again and see if you can connect.

![screenshot_20241031142016@2x](https://github.com/user-attachments/assets/8b29f562-643e-44f2-ab3c-ce8f0aa91901)

**Comment by airidasbrikas23** [comment]
Hey, I tried again at home and it's working. Thank you!

Cool with the image feature.
