### ISSUE TITLE
Feature request: Keyboard shortcuts to Regenrate response and select previous messages

### ISSUE THREAD

**Issue by airidasbrikas23** [iansinnott/prompta#57]
I appreciate user interfaces that are more keyboard-centric, and I like your vision for it.

I would love to have these two shortcuts:
- Regenerate Response
- Select the last message and then type to edit (using the up arrow key, similar to Slack or a terminal shell)

With both of these, it will be very easy to revise the prompt if the user realizes the wording was not precise enough and needs to add an extra word or something similar.

**Comment by iansinnott** [comment]
Regenerate response already has a quick action, so you can open the menu and start typing to get it quickly.

![screenshot_20241031231917@2x](https://github.com/user-attachments/assets/47019338-706e-4455-b340-3769bb06a7cb)

You can also edit previous messages, but you need to click it with the mouse to expose the edit button. I think Slack has a decent approach to doing this with the keyboard. However, I don't find myself doing this much, so I have no plans to add keyboard functionality. I just use the mouse.

![screenshot_20241031232152@2x](https://github.com/user-attachments/assets/1c03d443-942a-41e0-8b11-3d0bf74a8d34)

PRs welcome :)

**Comment by Brikas** [comment]
How do I open the start menu with keyboard?

**Comment by iansinnott** [comment]
Start menu?
