### ISSUE TITLE
Feature request: Providers from different LLMs

### ISSUE THREAD

**Issue by Brikas** [iansinnott/prompta#58]
After visiting other Chat UI providers, I came back to Prompta. This one is just very clean.

But one thing that makes me go back to the others is that they support more than OpenAI. I would love to be able to use Claude with Anthropic API key or Gemini with Google API key.

**Comment by iansinnott** [comment]
Funny you should ask, Anthropic support is in beta: https://github.com/iansinnott/prompta/pull/59

You can try it out here: https://prompta-ee4i1r4wl-ian-sinnotts-projects.vercel.app/

Will need to add your own API key.

However, no plans to add Gemini. It might be easy though. Could you link me to the documentation for the chat endpoint and the models endpoint? By implementing those two endpoints in OpenAI format, a new provider can be added.

Also, if you haven't yet, check out OpenRouter: https://openrouter.ai/docs#quick-start

You can use all the other LLMs through them.

**Comment by iansinnott** [comment]
You can now use anthropic directly, although not Google
