### ISSUE TITLE
Code snippets in responses are truncated in output

### ISSUE THREAD

**Issue by struanb** [iansinnott/prompta#60]
In recent weeks, I'm regularly seeing code snippets in responses truncated in the output.

You can see this is happening when you copy a (often suspiciously incomplete-looking) code snippets and paste it somewhere. Then you can see the output has truncated the snippets.

Check out this screenshot in which I copied the snippet and pasted it into the prompt buffer, so you can see for yourself.

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/540a2eb7-2f2c-49fc-8693-b7daecbafbf5" />

P.S. When you click reload, the code snippet is (often, or always; not sure) no longer truncated, as show here:

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/b656e2fe-3573-4a2a-a547-33b059995374" />

**Comment by iansinnott** [comment]
Thanks for this. I was able to repro. My guess is something to do with how Prompta handles markdown using the custom CodeBlock component.

**Comment by struanb** [comment]
This issue is still current. Here is my screen, following input of my initial prompt:

<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/15930a4a-c0e6-4f16-af0e-b39a7189e2f7" />

Here is my screen, having simply clicked 'reload' on the browser tab:

<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/8f3ff565-5e4a-40df-9fbb-2e60c7cd6250" />

**Comment by Brikas** [comment]
I can also confirm that the issue still exits.
