### ISSUE TITLE
How do I select whether its GPT4 or GPT 3.5?

### ISSUE THREAD

**Issue by Brikas** [iansinnott/prompta#9]

**Comment by iansinnott** [comment]
there is a settings screen where you can select the model: 

![screenshot_20231005021145](https://github.com/iansinnott/prompta/assets/3154865/7d5a05e5-d2d8-48cd-bde8-875a3b9892d0)

To get the settings screen you need to open the command palette. Either click on it in the lower right or press command+k

**Comment by NightMachinery** [comment]
This needs to be easier to do. A dropdown menu like the old ChatGPT UI is great.
